# yaml-language-server: $schema=../.vscode/schemas/nuitka-package-config.schema.json
# yamllint disable rule:line-length
# yamllint disable rule:indentation
# yamllint disable rule:comments-indentation
---
- module-name: 'flet_desktop'
  data-files:
    - dirs:
        - 'app'
    - patterns:
        - 'app/flet/*.exe'
      dest_path: 'app/flet'
      when: 'win32'
  dlls:
    - from_filenames:
        relative_path: 'app/flet'
        prefixes:
          - ''
        suffixes:
          - 'dll'
      dest_path: 'app/flet'
      when: 'win32'
